# Generated by Django 5.0.1 on 2024-01-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FN', models.CharField(default='', max_length=20)),
                ('LN', models.CharField(default='', max_length=20)),
                ('user', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=25)),
                ('contact', models.IntegerField(default='', max_length=15)),
                ('password', models.CharField(default='', max_length=15)),
                ('cpass', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
