# Generated by Django 5.0.1 on 2024-02-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d',
            name='contact',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
